//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.17 at 12:10:15 PM CEST 
//


package com.webservices;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.webservices package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Adres_QNAME = new QName("http://webservices.com", "Adres");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.webservices
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Adres }
     * 
     */
    public Adres createAdres() {
        return new Adres();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Adres }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.com", name = "Adres")
    public JAXBElement<Adres> createAdres(Adres value) {
        return new JAXBElement<Adres>(_Adres_QNAME, Adres.class, null, value);
    }

}
